networks:
  default:
    name: bard

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2
    ports:
      - "5672:5672"
    restart: always
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./postgres_initialization_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: always
  session_ender:
    container_name: session_ender
    # totoggle
    # image: bardrr/session_ender
    build: ../session_ender
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=user
      - PGPASSWORD=password
      - PGDATABASE=bard
    restart: always
    # totoggle
    command: npm run dev
