networks:
  default:
    name: bard

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2
    ports:
      - "5672:5672"
    restart: always
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    depends_on:
      - rabbitmq
    ports:
      - "8123:8123"
    restart: always
    volumes:
      - ch:/var/lib/clickhouse/
      - ch_logs:/val/log/clickhouse-server/
      - ./clickhouse_initialization_scripts:/docker-entrypoint-initdb.d
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ./postgres_initialization_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: always
  session_ender:
    container_name: session_ender
    # totoggle
    image: bardrr/session_ender
    #build: ../session_ender
    depends_on:
      - postgres
      - clickhouse
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=user
      - PGPASSWORD=password
      - PGDATABASE=bard
    restart: always
    # totoggle
    #command: npm run dev
  replayer:
    container_name: replayer
    image: bardrr/replayer:latest
    depends_on:
      - postgres
      - clickhouse
    restart: always
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=user
      - PGPASSWORD=password
      - PGDATABASE=bard
    ports:
      - "3003:3003"
volumes:
  ch:
  ch_logs:
